auth:
  strategy: anonymous

external_services:
  prometheus:
    url: "http://prometheus.monitoring.svc.cluster.local:9090"
  tracing:
    enabled: true
    provider: "tempo"
    in_cluster_url: "http://tempo.monitoring.svc.cluster.local:3200"

deployment:
  accessible_namespaces:
    - "**"
