# kind-cluster.yaml — 1 node kubeadm cluster (kind uses kubeadm internally)
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "auraops.io/environment=local"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
