apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aura-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aura-operator
subjects:
  - kind: ServiceAccount
    name: aura-operator
    namespace: auraops-system
