global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true
  agentDefaults:
    cpuRequest: "10m"
    cpuLimit: "50m"
    memRequest: "32Mi"
    memLimit: "64Mi"

server:
  dev:
    enabled: true
    devRootToken: "root"

  dataStorage:
    enabled: false
  
  auditStorage:
    enabled: false

ui:
  enabled: true
  serviceType: "ClusterIP"